import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"CMBC Radio Progreso 90.3 FM",
            artist: "Radio Progreso",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/JYy3a2sgTL.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://icecast.teveo.cu/XjfW7qWN",
            active: true,
        },
        {
            name:"Radio Havana",
            artist: "Havana",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/wBFBCeE72A.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://icecast.teveo.cu/McW3fLhs",
            active: false,
        },
        {
            name:"CMBD Radio Reloj 950 AM",
            artist: "AM",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/B7dTgwMGWB.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://icecast.teveo.cu/b3jbfThq",
            active: false,
        },
        {
            name:"Radio Martí",
            artist: "Radio Martí",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/8easq9waeqpa.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://n05.radiojar.com/3ds9yqpgq3quv?rj-ttl=5&rj-tok=AAABhDkQKzIA-Hz1HKTWg2CQzw",
            active: false,
        },
        {
            name:"CMBA Radio Rebelde FM",
            artist: "Radio Rebelde",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/KmEE8FKS6j.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://icecast.teveo.cu/zrXXWK9F",
            active: false,
        },
        {
            name:"CubanFlow radio",
            artist: "CubanFlow radio",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/eShhwvMESh.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://nap.casthost.net:9194/stream",
            active: false,
        },
        {
            name:"Salsa4te",
            artist: "Salsa",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/vryp5max4tzr.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://radiomusic.newradio.it/salsa4te?ext=.mp3",
            active: false,
        },
        {
            name:"Radio Enciclopedia",
            artist: "Radio Enciclopedia",
            cover: "https://dab-radios.org/admin_panel_radiocuba/uploads/radios/radio_50443_Radio%20Enciclopedia.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://icecast.teveo.cu/9Rnrbjzq",
            active: false,
        },
        {
            name:"La Reina Radial del Centro",
            artist: "La Reina Radial",
            cover: "https://dab-radios.org/admin_panel_radiocuba/uploads/radios/radio_77923_CMHW%20La%20Reina%20Radial%20del%20Centro.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://icecast.teveo.cu/TsxMM94R",
            active: false,
        },
        {
            name:"CMBV Radio Taino",
            artist: "Radio Taino",
            cover: "https://dab-radios.org/admin_panel_radiocuba/uploads/radios/radio_49144_Radio%20Taino.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/3MCwWg3V",
            active: false,
        },
        {
            name:"Radio Angulo",
            artist: "Radio Angulo",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/ujufa38dx4fg.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/hmVcdgM7",
            active: false,
        },
        {
            name:"Radio Ciudad Habana",
            artist: "Ciudad Habana",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/nuznrd2b8mfj.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/g73XCjCH",
            active: false,
        },
        {
            name:"Radio Sancti Spíritus",
            artist: "Radio Sancti",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/dutswqtmkz2u.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/NqWrgw7j",
            active: false,
        },
        {
            name:"Radio Musical Nacional",
            artist: "Musical Nacional",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/kxbcbmkza3ne.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/Nbtz7HT3",
            active: false,
        },
        {
            name:"Radio COCO",
            artist: "Radio COCO",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/yassynxxx3ud.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/fvc4RVRz",
            active: false,
        },
        {
            name:"Radio Ciudad del Mar",
            artist: "Radio Ciudad del Mar",
            cover: "https://dab-radios.org/admin_panel_radiocuba/uploads/radios/radio_92480_Radio%20Ciudad%20del%20Mar.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/CL7jRXqn",
            active: false,
        },
        {
            name:"Radio Cadena Agramonte",
            artist: "Radio Cadena",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/llxqd6drag6w.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/j99xztkT",
            active: false,
        },
        {
            name:"Radio Granma Manzanillo",
            artist: "Granma Manzanill",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/qjgjwtpnaf2v.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/9RLhkmRH",
            active: false,
        },
        {
            name:"Radio 26",
            artist: "Radio 26",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/svnfk3s9kced.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/LsxKNz7b",
            active: false,
        },
        {
            name:"Radio Trinchera",
            artist: "Trinchera",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/dqxgsf7hhgte.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/Csb3zdfv",
            active: false,
        },
        {
            name:"Radio Bayamo",
            artist: "Radio Bayamo",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/pxuw6wxctxkv.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/7hdNcTbM",
            active: false,
        },
        {
            name:"Salsa Mania",
            artist: "Salsa Mania",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/ndkxjm3k3thw.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ca2ssl.rcast.net/stream/60446.mp3",
            active: false,
        },
        {
            name:"Radio Archipiélago",
            artist: "Radio Archipiélago",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/j5ys4lm3ce4g.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radios.blumhost.es/8006/stream",
            active: false,
        },
        {
            name:"Radio Cadena",
            artist: "Radio Cadena",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/wqv46bsr447r.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/Jdq3Rbrg",
            active: false,
        },{
            name:"FM NEON-XL",
            artist: "FM NEON-XL",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/LkhfXLwmEd.webp",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s12.myradiostream.com/16754/listen.mp3",
            active: false,
        },
        {
            name:"Radio Moron",
            artist: "Radio Moron",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/ltjlr4sla3e9.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/jJ4JV3FK",
            active: false,
        },
        {
            name:"Radio Metropolitana",
            artist: "Radio Metropolitana",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/baydw5wnqmru.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/ktW3mW74",
            active: false,
        },
        {
            name:"Radio 1",
            artist: "Radio Angulo",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/ujufa38dx4fg.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/hmVcdgM7",
            active: false,
        },
        {
            name:"Radio Guamá",
            artist: "Radio Guamá",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/kukc3rqjjt62.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.teveo.cu/ngcdcV3k",
            active: false,
        },
        {
            name:"Radio Campesina Cubana",
            artist: "Radio Campesina Cubana",
            cover: "https://static2.mytuner.mobi/media/tvos_radios/gbwcgszgy5wf.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radiocampesinacubana.stream.laut.fm/radiocampesinacubana?t302=2022-10-11_16-20-10&uuid=ff3a781b-8812-4e8b-83b4-60196ae6b1af",
            active: false,
        },
    ];
}

export default chillHop;

